site_name: ZetsuBou
site_description: A self-hosted web application for your own image galleries and videos.
site_dir: front/doc_site
repo_url: https://github.com/ZetsuBouKyo/ZetsuBou
repo_name: ZetsuBouKyo/ZetsuBou
edit_uri: edit/master/docs/
copyright: Copyright (c) 2023-present ZetsuBouKyo and other contributors

theme:
  name: material
  favicon: assets/favicon.ico
  font: false
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - navigation.footer
    - navigation.tabs
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - git-revision-date-localized

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: ZetsuBouKyo
      repo: ZetsuBou
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ''
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - tables
  - md_in_html

extra_css:
- /docs/statics/termynal.css
- /docs/statics/custom.css

extra_javascript:
- /docs/statics/termynal.js
- /docs/statics/custom.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ZetsuBouKyo/ZetsuBou
    - icon: fontawesome/brands/twitch
      link: https://www.twitch.tv/zetsuboukyo

nav:
  - Welcome: index.md
  - Getting Started:
    - Launch an example: getting-started/launch-an-example.md
  - User Notes:
    - Searching: user-notes/searching.md
  - Developer Notes:
    - Architecture: developer-notes/architecture.md
    - Environments: developer-notes/environments.md
