version: "2"

services:
  grafana:
    image: grafana/grafana-oss:9.5.2
    user: "104"
    network_mode: host
    expose:
      - 3030
    volumes:
      - ${GRAFANA_DATA:-./dev/volumes/grafana/data}:/var/lib/grafana
      - ${GRAFANA_PROVISIONING:-./dev/volumes/grafana/provisioning}:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_HTTP_PORT=${GRAFANA_SERVER_HTTP_PORT:-3030}
