/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    IconClarityCursorArrowSolid: typeof import("~icons/clarity/cursor-arrow-solid")["default"];
    IconEntypoSave: typeof import("~icons/entypo/save")["default"];
    IconEosIconsLoading: typeof import("~icons/eos-icons/loading")["default"];
    IconFaGroup: typeof import("~icons/fa/group")["default"];
    IconIcBaselineConstruction: typeof import("~icons/ic/baseline-construction")["default"];
    IconIcBaselineGroup: typeof import("~icons/ic/baseline-group")["default"];
    IconIcBaselinePerson: typeof import("~icons/ic/baseline-person")["default"];
    IconIcBaselinePhotoCamera: typeof import("~icons/ic/baseline-photo-camera")["default"];
    IconIcBaselineSearch: typeof import("~icons/ic/baseline-search")["default"];
    IconIcBaselineSecurity: typeof import("~icons/ic/baseline-security")["default"];
    IconIcons8TodoList: typeof import("~icons/icons8/todo-list")["default"];
    IconIcOutlineAnalytics: typeof import("~icons/ic/outline-analytics")["default"];
    IconIcOutlineEdit: typeof import("~icons/ic/outline-edit")["default"];
    IconIcRoundExpandLess: typeof import("~icons/ic/round-expand-less")["default"];
    IconIcRoundExpandMore: typeof import("~icons/ic/round-expand-more")["default"];
    IconIcRoundKeyboardArrowLeft: typeof import("~icons/ic/round-keyboard-arrow-left")["default"];
    IconIcRoundKeyboardArrowRight: typeof import("~icons/ic/round-keyboard-arrow-right")["default"];
    IconIcRoundLink: typeof import("~icons/ic/round-link")["default"];
    IconIcRoundStopCircle: typeof import("~icons/ic/round-stop-circle")["default"];
    IconIcSharpPlayCircleFilled: typeof import("~icons/ic/sharp-play-circle-filled")["default"];
    IconIonIosPricetags: typeof import("~icons/ion/ios-pricetags")["default"];
    IconMdiChevronDoubleLeft: typeof import("~icons/mdi/chevron-double-left")["default"];
    IconMdiChevronDoubleRight: typeof import("~icons/mdi/chevron-double-right")["default"];
    IconMdiChevronLeft: typeof import("~icons/mdi/chevron-left")["default"];
    IconMdiChevronRight: typeof import("~icons/mdi/chevron-right")["default"];
    IconMdiCodeJson: typeof import("~icons/mdi/code-json")["default"];
    IconMdiFileEditOutline: typeof import("~icons/mdi/file-edit-outline")["default"];
    IconMdiStorage: typeof import("~icons/mdi/storage")["default"];
    IconMdiTrashCanOutline: typeof import("~icons/mdi/trash-can-outline")["default"];
    IconMdiUserSettingsVariant: typeof import("~icons/mdi/user-settings-variant")["default"];
    IconMdiVectorPolygon: typeof import("~icons/mdi/vector-polygon")["default"];
    IconOcticonSignOut: typeof import("~icons/octicon/sign-out")["default"];
    IconRiArrowGoBackFill: typeof import("~icons/ri/arrow-go-back-fill")["default"];
    IconWhhLayerorderup: typeof import("~icons/whh/layerorderup")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
  }
}
